### ISSUE TITLE
please submit to CRAN

### ISSUE THREAD

**Issue by ttriche** [wbuchanan/regexPipes#1]
package is supremely useful when trolling through karyotypes, etc.

**Comment by wbuchanan** [comment]
Submit package to CRAN

| Step 1 | Step 2 | Step 3 |
| --- | --- | --- |
| (Upload) | (Submission) | (Confirmation) |

The package has been uploaded successfully to CRAN

You will be redirected back to the CRAN homepage shortly

**Comment by ttriche** [comment]
you rock

--t

On Mon, Sep 12, 2016 at 11:06 AM, William Buchanan <notifications@github.com

**Comment by wbuchanan** [comment]
I try to take care of the simple things easily when possible.

**Comment by wbuchanan** [comment]
It should be live on CRAN now.

**Comment by ttriche** [comment]
it is indeed. thanks!

--t

**Comment by wbuchanan** [comment]
Not a problem.
